<?php
//DEFINICION DE LAS CONSTANTES CON LA URL DEL PROYECTO DONDE SE ENCUENTRA ALMACENADO EN ESTE CASO ACA
//YA EN SERVIDOR SERÍA EN LA CARPETA VAR/HTML/
define('URL', 'http://localhost/PHP/ControlGastos');
//DEFINIMOS LOS VALORES QUE TIENEN LAS CONSTANTES Y UTILIZARÁ LA FUNCIÓN CONNECT PARA CONECTARSE A LA DB
define('HOST','localhost');
define('DB', 'expenseapp');
define('USER','root');
define('PASSWORD','');
define('CHARSET','utf8mb4');
